# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-edge-platform"
BBFILE_PATTERN_meta-edge-platform = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-edge-platform = "6"

LAYERDEPENDS_meta-edge-platform = "core"
LAYERSERIES_COMPAT_meta-edge-platform = "scarthgap"
