# Inherit settings from the default Yocto reference distro
require conf/distro/poky.conf

# Distro Identity
DISTRO = "device-base"
DISTRO_NAME = "Device Base Platform"
DISTRO_VERSION = "2.0.0"
DISTRO_CODENAME = "scarthgap"

DISTRO_FEATURES:append = " systemd usrmerge overlayfs"
VIRTUAL-RUNTIME_init_manager = "systemd"
DISTRO_FEATURES_BACKFILL_CONSIDERED += "sysvinit"
VIRTUAL-RUNTIME_initscripts = "systemd-compat-units"
