ctrl_interface=/var/run/wpa_supplicant
ctrl_interface_group=0
update_config=1

network={
    ssid="uofm-secure"
    key_mgmt=WPA-EAP
    eap=PEAP
    identity="@UOFM_IDENTITY@"
    password="@UOFM_PASSWORD@"
    phase2="auth=MSCHAPV2"
    priority=20
}

network={
    ssid="@HOTSPOT_SSID@"
    psk="@HOTSPOT_PSK@"
    priority=10
}
